#############################################################################
# Makefile for building: videoGUI.app/Contents/MacOS/videoGUI
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  ../videoGUI/videoGUI.pro
# Template: app
# Command: /Users/sergiovergaratorres/Qt5.8.0/5.8/clang_64/bin/qmake -o Makefile ../videoGUI/videoGUI.pro -spec macx-g++ CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/usr/bin/gcc
CXX           = /Applications/Xcode.app/Contents/Developer/usr/bin/g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I../videoGUI -I. -I../Qt5.8.0/5.8/clang_64/lib/QtMultimediaWidgets.framework/Headers -I../Qt5.8.0/5.8/clang_64/lib/QtMultimedia.framework/Headers -I../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers -I../Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers -I../Qt5.8.0/5.8/clang_64/lib/QtNetwork.framework/Headers -I../Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../Qt5.8.0/5.8/clang_64/mkspecs/macx-g++ -F/Users/sergiovergaratorres/Qt5.8.0/5.8/clang_64/lib
QMAKE         = /Users/sergiovergaratorres/Qt5.8.0/5.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = videoGUI1.0.0
DISTDIR = /Users/sergiovergaratorres/build-videoGUI-Unnamed_f733e7-Debug/.tmp/videoGUI1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/usr/bin/g++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_LFLAGS) -Wl,-rpath,/Users/sergiovergaratorres/Qt5.8.0/5.8/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/sergiovergaratorres/Qt5.8.0/5.8/clang_64/lib -framework QtMultimediaWidgets -framework QtMultimedia -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework QtWidgets -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../videoGUI/main.cpp \
		../videoGUI/mainwindow.cpp qrc_resources.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qrc_resources.o \
		moc_mainwindow.o
DIST          = ../Qt5.8.0/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/qdevice.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/device_config.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/common/unix.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/common/mac.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/common/macx.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/common/sanitize.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/common/g++-base.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/common/g++-macx.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/qconfig.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/qt_config.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/macx-g++/qmake.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/spec_post.prf \
		../videoGUI/.qmake.stash \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/toolchain.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/default_pre.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/default_post.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/qml_debug.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/warn_on.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/qt.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/resources.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/moc.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/uic.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/file_copies.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/exceptions.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/yacc.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/lex.prf \
		../videoGUI/videoGUI.pro ../videoGUI/mainwindow.h ../videoGUI/main.cpp \
		../videoGUI/mainwindow.cpp
QMAKE_TARGET  = videoGUI
DESTDIR       = 
TARGET        = videoGUI.app/Contents/MacOS/videoGUI


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d videoGUI.app/Contents/MacOS/ || mkdir -p videoGUI.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../videoGUI/videoGUI.pro ../Qt5.8.0/5.8/clang_64/mkspecs/macx-g++/qmake.conf ../Qt5.8.0/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/qdevice.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/device_config.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/common/unix.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/common/mac.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/common/macx.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/common/sanitize.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/common/g++-base.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/common/g++-macx.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/qconfig.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/qt_config.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/macx-g++/qmake.conf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/toolchain.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/default_pre.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/default_post.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/qml_debug.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/warn_on.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/qt.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/resources.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/moc.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/uic.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/file_copies.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/exceptions.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/yacc.prf \
		../Qt5.8.0/5.8/clang_64/mkspecs/features/lex.prf \
		../videoGUI/videoGUI.pro \
		../videoGUI/resources.qrc \
		../Qt5.8.0/5.8/clang_64/lib/QtMultimediaWidgets.framework/QtMultimediaWidgets.prl \
		../Qt5.8.0/5.8/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../Qt5.8.0/5.8/clang_64/lib/QtGui.framework/QtGui.prl \
		../Qt5.8.0/5.8/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../Qt5.8.0/5.8/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile ../videoGUI/videoGUI.pro -spec macx-g++ CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../Qt5.8.0/5.8/clang_64/mkspecs/features/spec_pre.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/qdevice.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/features/device_config.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/common/unix.conf:
../Qt5.8.0/5.8/clang_64/mkspecs/common/mac.conf:
../Qt5.8.0/5.8/clang_64/mkspecs/common/macx.conf:
../Qt5.8.0/5.8/clang_64/mkspecs/common/sanitize.conf:
../Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base.conf:
../Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
../Qt5.8.0/5.8/clang_64/mkspecs/common/g++-base.conf:
../Qt5.8.0/5.8/clang_64/mkspecs/common/g++-macx.conf:
../Qt5.8.0/5.8/clang_64/mkspecs/qconfig.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt5.8.0/5.8/clang_64/mkspecs/features/qt_functions.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/qt_config.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/macx-g++/qmake.conf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt5.8.0/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/sdk.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/toolchain.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/default_pre.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/resolve_config.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/default_post.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_post.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/qml_debug.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/warn_on.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/qt.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/resources.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/moc.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/unix/opengl.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/uic.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/unix/thread.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/qmake_use.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/file_copies.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/rez.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/testcase_targets.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/exceptions.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/yacc.prf:
../Qt5.8.0/5.8/clang_64/mkspecs/features/lex.prf:
../videoGUI/videoGUI.pro:
../videoGUI/resources.qrc:
../Qt5.8.0/5.8/clang_64/lib/QtMultimediaWidgets.framework/QtMultimediaWidgets.prl:
../Qt5.8.0/5.8/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl:
../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../Qt5.8.0/5.8/clang_64/lib/QtGui.framework/QtGui.prl:
../Qt5.8.0/5.8/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../Qt5.8.0/5.8/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../videoGUI/videoGUI.pro -spec macx-g++ CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

videoGUI.app/Contents/PkgInfo: 
	@test -d videoGUI.app/Contents || mkdir -p videoGUI.app/Contents
	@$(DEL_FILE) videoGUI.app/Contents/PkgInfo
	@echo "APPL????" > videoGUI.app/Contents/PkgInfo
videoGUI.app/Contents/Resources/empty.lproj: 
	@test -d videoGUI.app/Contents/Resources || mkdir -p videoGUI.app/Contents/Resources
	@touch videoGUI.app/Contents/Resources/empty.lproj
	
videoGUI.app/Contents/Info.plist: 
	@test -d videoGUI.app/Contents || mkdir -p videoGUI.app/Contents
	@$(DEL_FILE) videoGUI.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.videoGUI,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,videoGUI,g" -e "s,@LIBRARY@,videoGUI,g" -e "s,@TYPEINFO@,????,g" ../Qt5.8.0/5.8/clang_64/mkspecs/macx-g++/Info.plist.app >videoGUI.app/Contents/Info.plist

all: Makefile \
		videoGUI.app/Contents/PkgInfo \
		videoGUI.app/Contents/Resources/empty.lproj \
		videoGUI.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../videoGUI/resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../Qt5.8.0/5.8/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../videoGUI/mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents ../videoGUI/main.cpp ../videoGUI/mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../videoGUI/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r videoGUI.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: ../videoGUI/resources.qrc \
		../Qt5.8.0/5.8/clang_64/bin/rcc \
		../videoGUI/redo-icon-24337.png \
		../videoGUI/media-volume-3.png \
		../videoGUI/Magnifying_glass_icon.png \
		../videoGUI/open_256.png \
		../videoGUI/shape_square-512.png \
		../videoGUI/10513.png \
		../videoGUI/Icons8-Windows-8-Media-Controls-Pause.ico \
		../videoGUI/Arrows.icon.png \
		../videoGUI/curved-black-line-clip-art-at-clker-com-vector-clip-art-online-rIt2rw-clipart.png \
		../videoGUI/player-stop-frame-video-music-512.png \
		../videoGUI/_color_palette-512.png \
		../videoGUI/circle-icon-0.png \
		../videoGUI/375.png \
		../videoGUI/Icons8-Ios7-Editing-Line.ico \
		../videoGUI/arrow-pointing-to-right_318-50470.jpg \
		../videoGUI/159121.png \
		../videoGUI/Entertainment_film_film_reel_film_roll_movie_reel_roll_theate-512.png
	/Users/sergiovergaratorres/Qt5.8.0/5.8/clang_64/bin/rcc -name resources ../videoGUI/resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../Qt5.8.0/5.8/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/usr/bin/g++ -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../Qt5.8.0/5.8/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt5.8.0/5.8/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../Qt5.8.0/5.8/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../Qt5.8.0/5.8/clang_64/lib/QtMultimediaWidgets.framework/Headers/QVideoWidget \
		../Qt5.8.0/5.8/clang_64/lib/QtMultimediaWidgets.framework/Headers/qvideowidget.h \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QProgressBar \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/Qslider \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../videoGUI/mainwindow.h \
		moc_predefs.h \
		../Qt5.8.0/5.8/clang_64/bin/moc
	/Users/sergiovergaratorres/Qt5.8.0/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/sergiovergaratorres/Qt5.8.0/5.8/clang_64/mkspecs/macx-g++ -I/Users/sergiovergaratorres/videoGUI -I/Users/sergiovergaratorres/Qt5.8.0/5.8/clang_64/lib/QtMultimediaWidgets.framework/Headers -I/Users/sergiovergaratorres/Qt5.8.0/5.8/clang_64/lib/QtMultimedia.framework/Headers -I/Users/sergiovergaratorres/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/sergiovergaratorres/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/sergiovergaratorres/Qt5.8.0/5.8/clang_64/lib/QtNetwork.framework/Headers -I/Users/sergiovergaratorres/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/sergiovergaratorres/Qt5.8.0/5.8/clang_64/lib ../videoGUI/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ../videoGUI/mainwindow.ui \
		../Qt5.8.0/5.8/clang_64/bin/uic
	/Users/sergiovergaratorres/Qt5.8.0/5.8/clang_64/bin/uic ../videoGUI/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../videoGUI/main.cpp ../videoGUI/mainwindow.h \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt5.8.0/5.8/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../Qt5.8.0/5.8/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../Qt5.8.0/5.8/clang_64/lib/QtMultimediaWidgets.framework/Headers/QVideoWidget \
		../Qt5.8.0/5.8/clang_64/lib/QtMultimediaWidgets.framework/Headers/qvideowidget.h \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QProgressBar \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/Qslider \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../videoGUI/main.cpp

mainwindow.o: ../videoGUI/mainwindow.cpp ../videoGUI/mainwindow.h \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt5.8.0/5.8/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../Qt5.8.0/5.8/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../Qt5.8.0/5.8/clang_64/lib/QtMultimediaWidgets.framework/Headers/QVideoWidget \
		../Qt5.8.0/5.8/clang_64/lib/QtMultimediaWidgets.framework/Headers/qvideowidget.h \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QProgressBar \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/Qslider \
		../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../videoGUI/mainwindow.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

